/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.chuong2.BaiTap_Lap4;

import javax.swing.SwingWorker;

/**
 *
 * @author DELL
 */
public class Lap4_Bai1 extends javax.swing.JFrame {

    /**
     * Creates new form Lap4_Bai1
     */
    public Lap4_Bai1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCountdown = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        txtSeconds = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCountdown.setText("Thời gian:");

        btnStart.setText("Bắt đầu");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btnStart))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCountdown)
                            .addComponent(txtSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnStart)
                .addGap(18, 18, 18)
                .addComponent(lblCountdown)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        int totalSeconds;
            try {
                totalSeconds = Integer.parseInt(txtSeconds.getText().trim());
                if (totalSeconds <= 0) {
                    lblCountdown.setText("Vui lòng nhập số giây > 0!");
                    return;
                }
            } catch (NumberFormatException e) {
                lblCountdown.setText("Số giây không hợp lệ!");
                return;
            }
        SwingWorker<Void, Integer> worker = new SwingWorker<Void, Integer>() {
        
            @Override
            protected Void doInBackground() throws Exception {
                // Vòng lặp đếm ngược từng giây một
                for (int i = totalSeconds; i >= 0; i--) {
                    publish(i);          // Đẩy số giây còn lại sang hàm process()
                    Thread.sleep(1000);   // Tạm dừng 1 giây ở luồng ẩn
                }
                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                // Lấy số giây còn lại mới nhất
                int remaining = chunks.get(chunks.size() - 1);
                lblCountdown.setText("Thời gian còn lại: " + remaining + " giây");
            }

            @Override
            protected void done() {
                // Khi đếm ngược xong (i = 0)
                lblCountdown.setText("Hết giờ!");
                btnStart.setEnabled(true);   // Mở lại nút bấm
                txtSeconds.setEnabled(true); // Mở lại ô nhập
            }
        };

        // 4. Bắt đầu chạy luồng đếm ngược
        worker.execute();
        
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lap4_Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lap4_Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lap4_Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lap4_Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lap4_Bai1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel lblCountdown;
    private javax.swing.JTextField txtSeconds;
    // End of variables declaration//GEN-END:variables
}
