/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.chuong2.BaiTap_Lap4;

import javax.swing.SwingWorker;

/**
 *
 * @author DELL
 */
public class Lap4_Bai4 extends javax.swing.JFrame {

    /**
     * Creates new form Lap4_Bai4
     */
    public Lap4_Bai4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtN = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        prgBar = new javax.swing.JProgressBar();
        lblResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnFind.setText("Tìm");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        prgBar.setStringPainted(true);

        lblResult.setText("Kết quả: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtN)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(prgBar, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(lblResult)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFind)
                .addGap(28, 28, 28)
                .addComponent(prgBar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblResult)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        // 1. Kiểm tra dữ liệu đầu vào
        int n;
        try {
            n = Integer.parseInt(txtN.getText().trim());
            if (n < 0) {
                lblResult.setText("Vui lòng nhập N >= 0!");
                return;
            }
        } catch (NumberFormatException e) {
            lblResult.setText("N phải là số nguyên hợp lệ!");
            return;
        }

        // 2. Khóa giao diện ban đầu
        btnFind.setEnabled(false);
        prgBar.setValue(0);
        lblResult.setText("Đang tính toán...");

        // 3. Khởi tạo SwingWorker
        // - java.math.BigInteger: Kiểu dữ liệu kết quả (tránh tràn số khi N lớn)
        // - Integer: Phần trăm tiến độ (0 - 100%)
        SwingWorker<java.math.BigInteger, Integer> worker = new SwingWorker<java.math.BigInteger, Integer>() {

            // Bảng ghi nhớ memoization bằng Map
            private final java.util.Map<Integer, java.math.BigInteger> memo = new java.util.HashMap<>();

            // Hàm tính Fibonacci có Memoization
            private java.math.BigInteger fibonacci(int k) {
                if (k == 0) return java.math.BigInteger.ZERO;
                if (k == 1) return java.math.BigInteger.ONE;

                // Nếu đã tính rồi thì lấy từ Bảng nhớ ra dùng lại
                if (memo.containsKey(k)) {
                    return memo.get(k);
                }

                // Chưa tính thì tính rồi lưu vào Bảng nhớ
                java.math.BigInteger result = fibonacci(k - 1).add(fibonacci(k - 2));
                memo.put(k, result);
                return result;
            }

            @Override
            protected java.math.BigInteger doInBackground() throws Exception {
               
                if (n == 0) {
                    publish(100);
                    return java.math.BigInteger.ZERO;
                }
                if (n == 1) {
                    publish(100);
                    return java.math.BigInteger.ONE;
                }

                // Với N >= 2, chạy vòng lặp bình thường
                for (int i = 1; i <= n; i++) {
                    fibonacci(i); // Tính và ghi nhớ

                    int progress = (int) (((double) i / n) * 100);
                    publish(progress);

                    if (n <= 100) {
                        Thread.sleep(10);
                    }
                }

                return memo.get(n);
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                // Cập nhật giá trị tiến trình lên JProgressBar
                int currentProgress = chunks.get(chunks.size() - 1);
                prgBar.setValue(currentProgress);
            }

            @Override
            protected void done() {
                try {
                    // Lấy kết quả BigInteger từ doInBackground()
                    java.math.BigInteger result = get();

                    // Rút gọn chuỗi hiển thị nếu số quá dài
                    String strResult = result.toString();
                    if (strResult.length() > 50) {
                        lblResult.setText("F(" + n + ") = " + strResult.substring(0, 20) + "..." + " (" + strResult.length() + " chữ số)");
                    } else {
                        lblResult.setText("F(" + n + ") = " + strResult);
                    }
                } catch (Exception e) {
                    lblResult.setText("Lỗi trong quá trình tính toán!");
                } finally {
                    prgBar.setValue(100);
                    btnFind.setEnabled(true); // Mở lại nút bấm
                }
            }
        };

        // 4. Chạy tiến trình
        worker.execute();
    }//GEN-LAST:event_btnFindActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lap4_Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lap4_Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lap4_Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lap4_Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lap4_Bai4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JLabel lblResult;
    private javax.swing.JProgressBar prgBar;
    private javax.swing.JTextField txtN;
    // End of variables declaration//GEN-END:variables
}
