/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.chuong2.BaiTap_Lap4;

import javax.swing.SwingWorker;

/**
 *
 * @author DELL
 */
public class Lap4_Bai3 extends javax.swing.JFrame {

    /**
     * Creates new form Lap4_Bai3
     */
    public Lap4_Bai3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtn = new javax.swing.JTextField();
        btnTinh = new javax.swing.JButton();
        prgBar = new javax.swing.JProgressBar();
        lbkq = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTinh.setText("Tính");
        btnTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhActionPerformed(evt);
            }
        });

        prgBar.setStringPainted(true);

        lbkq.setText("Kết quả: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnTinh))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(lbkq))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(txtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(prgBar, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(txtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTinh)
                .addGap(35, 35, 35)
                .addComponent(prgBar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lbkq)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhActionPerformed
        // TODO add your handling code here:
        int n;
        try {
            n = Integer.parseInt(txtn.getText().trim());
            if (n <= 2) {
                lbkq.setText("Vui lòng nhập N > 2!");
                return;
            }
        } catch (NumberFormatException e) {
            lbkq.setText("N phải là số nguyên hợp lệ!");
            return;
        }
 
        SwingWorker<Long, Integer> worker = new SwingWorker<Long, Integer>() {

            // Hàm kiểm tra số nguyên tố
            private boolean isPrime(int number) {
                if (number < 2) return false;
                for (int i = 2; i <= Math.sqrt(number); i++) {
                    if (number % i == 0) return false;
                }
                return true;
            }

            @Override
            protected Long doInBackground() throws Exception {
                long sum = 0;
                
                for (int i = 2; i < n; i++) {
                    if (isPrime(i)) {
                        sum += i;
                    }

                    // Tính phần trăm hoàn thành và đẩy về luồng UI
                    int progress = (( i / (n - 1)) * 100);
                    publish(progress);

                    if (n <= 1000) {
                        Thread.sleep(10);
                    }
                }
                return sum; 
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int currentProgress = chunks.get(chunks.size() - 1);
                prgBar.setValue(currentProgress);
            }

            @Override
            protected void done() {
                try {
                    // get() lấy kết quả kiểu Long trả về từ doInBackground()
                    long totalSum = get(); 
                    lbkq.setText("Tổng các SNT < " + n + " là: " + totalSum);
                } catch (Exception e) {
                    lbkq.setText("Lỗi trong quá trình tính toán!");
                } 
            }
        };

        worker.execute();
    }//GEN-LAST:event_btnTinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lap4_Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lap4_Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lap4_Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lap4_Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lap4_Bai3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTinh;
    private javax.swing.JLabel lbkq;
    private javax.swing.JProgressBar prgBar;
    private javax.swing.JTextField txtn;
    // End of variables declaration//GEN-END:variables
}
