/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.chuong2.BaiTap_Lap4;

import java.util.List;
import javax.swing.JTextField;

/**
 *
 * @author DELL
 */
public class MainFrame extends javax.swing.JFrame {
    private java.util.List<Student> studentList = new java.util.ArrayList<>();
    private javax.swing.table.DefaultTableModel tableModel;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);

        // Lấy model từ JTable đã tạo trên giao diện NetBeans
        tableModel = (javax.swing.table.DefaultTableModel) tblStudents.getModel();

        // Xử lý sự kiện click chọn dòng
        tblStudents.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int row = tblStudents.getSelectedRow();
                if (row >= 0) {
                    // Lấy Mã SV từ cột index 1
                    String studentId = tableModel.getValueAt(row, 1).toString();

                    // Nếu dòng được chọn bị trống Mã SV (dòng môn thứ 2 trở đi), dò ngược lên dòng trên
                    while (studentId.isEmpty() && row > 0) {
                        row--;
                        studentId = tableModel.getValueAt(row, 1).toString();
                    }

                    // Tìm đối tượng Sinh viên tương ứng và đẩy lên Form
                    for (Student st : studentList) {
                        if (st.getId().equals(studentId)) {
                            txtId.setText(st.getId());
                            txtName.setText(st.getName());
                            txtNumSubjects.setText(String.valueOf(st.getSubjects().size()));
                            break;
                        }
                    }
                }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumSubjects = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin sinh viên", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Black", 0, 18))); // NOI18N
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        jLabel1.setText("                                                                                                   Mã SV");
        jPanel1.add(jLabel1);
        jPanel1.add(txtId);

        jLabel2.setText("                                                                                                   Họ tên");
        jPanel1.add(jLabel2);
        jPanel1.add(txtName);

        jLabel3.setText("                                                                                                   Số môn");
        jPanel1.add(jLabel3);
        jPanel1.add(txtNumSubjects);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã SV", "Họ tên", "Số môn", "Tên môn", "CC", "GK", "Ck", "ĐTB tích lũy "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblStudents);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Làm mới");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnAdd)
                .addGap(18, 18, 18)
                .addComponent(btnEdit)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addGap(18, 18, 18)
                .addComponent(btnClear)
                .addContainerGap(334, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String id = txtId.getText().trim();
        String name = txtName.getText().trim();
        String numStr = txtNumSubjects.getText().trim();

        if (id.isEmpty() || name.isEmpty() || numStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
            return;
        }

        try {
            int n = Integer.parseInt(numStr);
            if (n <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Số môn N phải > 0!");
                return;
            }

            java.util.List<Subject> subjects = inputSubjectsDialog(n, null);
            if (subjects != null) {
                Student st = new Student(id, name);
                st.setSubjects(subjects);
                studentList.add(st);
                renderTable();
                clearForm();
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Số môn phải là số nguyên!");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int row = tblStudents.getSelectedRow();
        if (row < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn sinh viên cần sửa!");
            return;
        }

        try {
            int n = Integer.parseInt(txtNumSubjects.getText().trim());
            Student st = studentList.get(row);

            java.util.List<Subject> subjects = inputSubjectsDialog(n, st.getSubjects());
            if (subjects != null) {
                st.setId(txtId.getText().trim());
                st.setName(txtName.getText().trim());
                st.setSubjects(subjects);
                renderTable();
                clearForm();
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Số môn phải là số nguyên!");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = tblStudents.getSelectedRow();
        if (row < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn sinh viên cần xóa!");
            return;
        }

        // Tìm Mã SV của dòng đang chọn
        String studentId = tableModel.getValueAt(row, 1).toString();
        while (studentId.isEmpty() && row > 0) {
            row--;
            studentId = tableModel.getValueAt(row, 1).toString();
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this, "Bạn có chắc chắn muốn xóa sinh viên này?", "Xác nhận xóa", javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // Tìm và xóa trong danh sách dữ liệu
            final String targetId = studentId;
            studentList.removeIf(st -> st.getId().equals(targetId));

            renderTable(); // Vẽ lại bảng
            clearForm();   // Xóa trắng form
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed
    
    private java.util.List<Subject> inputSubjectsDialog(int n, java.util.List<Subject> currentSubjects) {
        java.util.List<Subject> list = new java.util.ArrayList<>();
        for (int i = 0; i < n; i++) {
            Subject oldSub = (currentSubjects != null && i < currentSubjects.size()) ? currentSubjects.get(i) : null;

            JTextField fName = new JTextField(oldSub != null ? oldSub.getName() : "Môn " + (i + 1));
            JTextField fCC = new JTextField(oldSub != null ? String.valueOf(oldSub.getCc()) : "0");
            JTextField fGK = new JTextField(oldSub != null ? String.valueOf(oldSub.getGk()) : "0");
            JTextField fCK = new JTextField(oldSub != null ? String.valueOf(oldSub.getCk()) : "0");

            Object[] message = {
                "Tên môn:", fName,
                "Điểm Chuyên cần (20%):", fCC,
                "Điểm Giữa kỳ (30%):", fGK,
                "Điểm Cuối kỳ (50%):", fCK
            };

            int option = javax.swing.JOptionPane.showConfirmDialog(this, message, "Nhập môn " + (i + 1) + "/" + n, javax.swing.JOptionPane.OK_CANCEL_OPTION);
            if (option == javax.swing.JOptionPane.OK_OPTION) {
                try {
                    double cc = Double.parseDouble(fCC.getText());
                    double gk = Double.parseDouble(fGK.getText());
                    double ck = Double.parseDouble(fCK.getText());

                    if (cc < 0 || cc > 10 || gk < 0 || gk > 10 || ck < 0 || ck > 10) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Điểm phải từ 0-10!");
                        i--;
                        continue;
                    }
                    list.add(new Subject(fName.getText().trim(), cc, gk, ck));
                } catch (Exception e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Điểm phải là số!");
                    i--;
                }
            } else {
                return null;
            }
        }
        return list;
    }

    private void renderTable() {
        tableModel.setRowCount(0); // Xóa dữ liệu cũ trên bảng
        int stt = 1;

        for (Student st : studentList) {
            List<Subject> subjects = st.getSubjects();

            if (subjects.isEmpty()) {
                // Sinh viên chưa có môn nào
                tableModel.addRow(new Object[]{
                    stt++,
                    st.getId(),
                    st.getName(),
                    0,
                    "-", "-", "-", "-",
                    st.getGpa()
                });
            } else {
                // Duyệt từng môn học của sinh viên
                for (int i = 0; i < subjects.size(); i++) {
                    Subject sub = subjects.get(i);

                    if (i == 0) {
                        // Dòng môn đầu tiên: Hiển thị đầy đủ thông tin sinh viên
                        tableModel.addRow(new Object[]{
                            stt++,
                            st.getId(),
                            st.getName(),
                            subjects.size(),
                            sub.getName(),
                            sub.getCc(),
                            sub.getGk(),
                            sub.getCk(),
                            st.getGpa()
                        });
                    } else {
                        // Các dòng môn tiếp theo: Để trống thông tin chung
                        tableModel.addRow(new Object[]{
                            "", "", "", "",
                            sub.getName(),
                            sub.getCc(),
                            sub.getGk(),
                            sub.getCk(),
                            ""
                        });
                    }
                }
            }
        }
    }

    private void clearForm() {
        txtId.setText("");
        txtName.setText("");
        txtNumSubjects.setText("");
        tblStudents.clearSelection();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumSubjects;
    // End of variables declaration//GEN-END:variables
}
